# Change these first
owner: Whist-Team # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Whist-Server
    url: https://whist.haasen.eu
assignees:
  - Segelzwerg

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
